# Generated by Django 3.1.2 on 2020-10-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='VisitedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('date_visited', models.DateField()),
            ],
            options={
                'ordering': ['date_visited', 'url'],
            },
        ),
        migrations.CreateModel(
            name='JobLossMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=150)),
                ('country_name', models.CharField(max_length=150)),
                ('date_text', models.DateField()),
                ('language', models.CharField(max_length=30)),
                ('extracted_text', models.TextField()),
                ('entities_mentioned', models.TextField()),
                ('numbers_mentioned', models.TextField()),
                ('article_headline', models.TextField()),
                ('article_url', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_losses', to='main.country')),
            ],
            options={
                'ordering': ['publication_name', 'extracted_text', 'numbers_mentioned'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='main.date'),
        ),
    ]
