# Generated by Django 3.1.2 on 2020-10-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='date',
        ),
        migrations.RemoveField(
            model_name='joblossmention',
            name='country',
        ),
    ]
