# Generated by Django 3.1.2 on 2020-10-21 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201021_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='main.date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblossmention',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_losses', to='main.country'),
            preserve_default=False,
        ),
    ]
