# Generated by Django 3.1.2 on 2020-10-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201021_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblossmention',
            old_name='date_text',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='country',
            name='date',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
