# Generated by Django 3.1.2 on 2020-10-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201021_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblossmention',
            name='publication_date',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
