# Generated by Django 3.1.2 on 2020-10-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_joblossmention_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblossmention',
            name='dates_mentioned',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
