# Generated by Django 3.1.2 on 2020-10-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_joblossmention_dates_mentioned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblossmention',
            old_name='date',
            new_name='date_accessed',
        ),
    ]
